name: auto-complete

services:
  auto-complete-service:
    build: ./backend/AutoCompileService
    # network: auto-complete
    healthcheck:
      test: ["CMD", "grpcurl", "-plaintext", "localhost:50053", "list"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    ports:
      - "50053:50053"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped
  
  db:
    image: postgres:latest
    container_name: auto-complete-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: autocomplete-db
    # network: auto-complete
    ports:
      - "5432:5432"
    volumes:
      - autocomplete_data:/var/lib/postgresql/data
      - ./backend/AutoCompileService/internal/migrations/postgres-data:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d autocomplete-db" ]
      interval: 10s
      timeout: 10s
      retries: 5
    restart: unless-stopped

  redis:
    image: redis:6.2.6-alpine
    container_name: redis-container
    # network: auto-complete
    command: [ "redis-server", "--requirepass", "admin" ]
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "admin", "ping"]
      interval: 10s
      timeout: 5s
      retries: 10
    restart: unless-stopped
networks:
  auto-complete:
volumes:
  autocomplete_data:
  redis-data: