// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: auto-comlite.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AutoCompiteService_AutoComplite_FullMethodName = "/auto_complite.AutoCompiteService/AutoComplite"
)

// AutoCompiteServiceClient is the client API for AutoCompiteService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AutoCompiteServiceClient interface {
	AutoComplite(ctx context.Context, in *AutoCompliteRequest, opts ...grpc.CallOption) (*AutoCompileResponce, error)
}

type autoCompiteServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAutoCompiteServiceClient(cc grpc.ClientConnInterface) AutoCompiteServiceClient {
	return &autoCompiteServiceClient{cc}
}

func (c *autoCompiteServiceClient) AutoComplite(ctx context.Context, in *AutoCompliteRequest, opts ...grpc.CallOption) (*AutoCompileResponce, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AutoCompileResponce)
	err := c.cc.Invoke(ctx, AutoCompiteService_AutoComplite_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AutoCompiteServiceServer is the server API for AutoCompiteService service.
// All implementations must embed UnimplementedAutoCompiteServiceServer
// for forward compatibility.
type AutoCompiteServiceServer interface {
	AutoComplite(context.Context, *AutoCompliteRequest) (*AutoCompileResponce, error)
	mustEmbedUnimplementedAutoCompiteServiceServer()
}

// UnimplementedAutoCompiteServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAutoCompiteServiceServer struct{}

func (UnimplementedAutoCompiteServiceServer) AutoComplite(context.Context, *AutoCompliteRequest) (*AutoCompileResponce, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AutoComplite not implemented")
}
func (UnimplementedAutoCompiteServiceServer) mustEmbedUnimplementedAutoCompiteServiceServer() {}
func (UnimplementedAutoCompiteServiceServer) testEmbeddedByValue()                            {}

// UnsafeAutoCompiteServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AutoCompiteServiceServer will
// result in compilation errors.
type UnsafeAutoCompiteServiceServer interface {
	mustEmbedUnimplementedAutoCompiteServiceServer()
}

func RegisterAutoCompiteServiceServer(s grpc.ServiceRegistrar, srv AutoCompiteServiceServer) {
	// If the following call pancis, it indicates UnimplementedAutoCompiteServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AutoCompiteService_ServiceDesc, srv)
}

func _AutoCompiteService_AutoComplite_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AutoCompliteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AutoCompiteServiceServer).AutoComplite(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AutoCompiteService_AutoComplite_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AutoCompiteServiceServer).AutoComplite(ctx, req.(*AutoCompliteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AutoCompiteService_ServiceDesc is the grpc.ServiceDesc for AutoCompiteService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AutoCompiteService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "auto_complite.AutoCompiteService",
	HandlerType: (*AutoCompiteServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AutoComplite",
			Handler:    _AutoCompiteService_AutoComplite_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "auto-comlite.proto",
}
