// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: auto-complete.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AutoCompleteService_AutoComplete_FullMethodName = "/auto_complete.AutoCompleteService/AutoComplete"
)

// AutoCompleteServiceClient is the client API for AutoCompleteService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AutoCompleteServiceClient interface {
	AutoComplete(ctx context.Context, in *AutoCompleteRequest, opts ...grpc.CallOption) (*AutoCompleteResponse, error)
}

type autoCompleteServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAutoCompleteServiceClient(cc grpc.ClientConnInterface) AutoCompleteServiceClient {
	return &autoCompleteServiceClient{cc}
}

func (c *autoCompleteServiceClient) AutoComplete(ctx context.Context, in *AutoCompleteRequest, opts ...grpc.CallOption) (*AutoCompleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AutoCompleteResponse)
	err := c.cc.Invoke(ctx, AutoCompleteService_AutoComplete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AutoCompleteServiceServer is the server API for AutoCompleteService service.
// All implementations must embed UnimplementedAutoCompleteServiceServer
// for forward compatibility.
type AutoCompleteServiceServer interface {
	AutoComplete(context.Context, *AutoCompleteRequest) (*AutoCompleteResponse, error)
	mustEmbedUnimplementedAutoCompleteServiceServer()
}

// UnimplementedAutoCompleteServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAutoCompleteServiceServer struct{}

func (UnimplementedAutoCompleteServiceServer) AutoComplete(context.Context, *AutoCompleteRequest) (*AutoCompleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AutoComplete not implemented")
}
func (UnimplementedAutoCompleteServiceServer) mustEmbedUnimplementedAutoCompleteServiceServer() {}
func (UnimplementedAutoCompleteServiceServer) testEmbeddedByValue()                             {}

// UnsafeAutoCompleteServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AutoCompleteServiceServer will
// result in compilation errors.
type UnsafeAutoCompleteServiceServer interface {
	mustEmbedUnimplementedAutoCompleteServiceServer()
}

func RegisterAutoCompleteServiceServer(s grpc.ServiceRegistrar, srv AutoCompleteServiceServer) {
	// If the following call pancis, it indicates UnimplementedAutoCompleteServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AutoCompleteService_ServiceDesc, srv)
}

func _AutoCompleteService_AutoComplete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AutoCompleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AutoCompleteServiceServer).AutoComplete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AutoCompleteService_AutoComplete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AutoCompleteServiceServer).AutoComplete(ctx, req.(*AutoCompleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AutoCompleteService_ServiceDesc is the grpc.ServiceDesc for AutoCompleteService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AutoCompleteService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "auto_complete.AutoCompleteService",
	HandlerType: (*AutoCompleteServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AutoComplete",
			Handler:    _AutoCompleteService_AutoComplete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "auto-complete.proto",
}
