// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: auto-comlite.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AutoCompliteRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OriginalString string                 `protobuf:"bytes,1,opt,name=originalString,proto3" json:"originalString,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AutoCompliteRequest) Reset() {
	*x = AutoCompliteRequest{}
	mi := &file_auto_comlite_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AutoCompliteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AutoCompliteRequest) ProtoMessage() {}

func (x *AutoCompliteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auto_comlite_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AutoCompliteRequest.ProtoReflect.Descriptor instead.
func (*AutoCompliteRequest) Descriptor() ([]byte, []int) {
	return file_auto_comlite_proto_rawDescGZIP(), []int{0}
}

func (x *AutoCompliteRequest) GetOriginalString() string {
	if x != nil {
		return x.OriginalString
	}
	return ""
}

type AutoCompileResponce struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	PrepositionsStrings []string               `protobuf:"bytes,1,rep,name=PrepositionsStrings,proto3" json:"PrepositionsStrings,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *AutoCompileResponce) Reset() {
	*x = AutoCompileResponce{}
	mi := &file_auto_comlite_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AutoCompileResponce) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AutoCompileResponce) ProtoMessage() {}

func (x *AutoCompileResponce) ProtoReflect() protoreflect.Message {
	mi := &file_auto_comlite_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AutoCompileResponce.ProtoReflect.Descriptor instead.
func (*AutoCompileResponce) Descriptor() ([]byte, []int) {
	return file_auto_comlite_proto_rawDescGZIP(), []int{1}
}

func (x *AutoCompileResponce) GetPrepositionsStrings() []string {
	if x != nil {
		return x.PrepositionsStrings
	}
	return nil
}

var File_auto_comlite_proto protoreflect.FileDescriptor

const file_auto_comlite_proto_rawDesc = "" +
	"\n" +
	"\x12auto-comlite.proto\x12\rauto_complite\"=\n" +
	"\x13AutoCompliteRequest\x12&\n" +
	"\x0eoriginalString\x18\x01 \x01(\tR\x0eoriginalString\"G\n" +
	"\x13AutoCompileResponce\x120\n" +
	"\x13PrepositionsStrings\x18\x01 \x03(\tR\x13PrepositionsStrings2l\n" +
	"\x12AutoCompiteService\x12V\n" +
	"\fAutoComplite\x12\".auto_complite.AutoCompliteRequest\x1a\".auto_complite.AutoCompileResponceB\x0eZ\finternal/apib\x06proto3"

var (
	file_auto_comlite_proto_rawDescOnce sync.Once
	file_auto_comlite_proto_rawDescData []byte
)

func file_auto_comlite_proto_rawDescGZIP() []byte {
	file_auto_comlite_proto_rawDescOnce.Do(func() {
		file_auto_comlite_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_auto_comlite_proto_rawDesc), len(file_auto_comlite_proto_rawDesc)))
	})
	return file_auto_comlite_proto_rawDescData
}

var file_auto_comlite_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_auto_comlite_proto_goTypes = []any{
	(*AutoCompliteRequest)(nil), // 0: auto_complite.AutoCompliteRequest
	(*AutoCompileResponce)(nil), // 1: auto_complite.AutoCompileResponce
}
var file_auto_comlite_proto_depIdxs = []int32{
	0, // 0: auto_complite.AutoCompiteService.AutoComplite:input_type -> auto_complite.AutoCompliteRequest
	1, // 1: auto_complite.AutoCompiteService.AutoComplite:output_type -> auto_complite.AutoCompileResponce
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_auto_comlite_proto_init() }
func file_auto_comlite_proto_init() {
	if File_auto_comlite_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_auto_comlite_proto_rawDesc), len(file_auto_comlite_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_auto_comlite_proto_goTypes,
		DependencyIndexes: file_auto_comlite_proto_depIdxs,
		MessageInfos:      file_auto_comlite_proto_msgTypes,
	}.Build()
	File_auto_comlite_proto = out.File
	file_auto_comlite_proto_goTypes = nil
	file_auto_comlite_proto_depIdxs = nil
}
