// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: auto-complete.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AutoCompleteRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OriginalString string                 `protobuf:"bytes,1,opt,name=originalString,proto3" json:"originalString,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AutoCompleteRequest) Reset() {
	*x = AutoCompleteRequest{}
	mi := &file_auto_complete_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AutoCompleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AutoCompleteRequest) ProtoMessage() {}

func (x *AutoCompleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auto_complete_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AutoCompleteRequest.ProtoReflect.Descriptor instead.
func (*AutoCompleteRequest) Descriptor() ([]byte, []int) {
	return file_auto_complete_proto_rawDescGZIP(), []int{0}
}

func (x *AutoCompleteRequest) GetOriginalString() string {
	if x != nil {
		return x.OriginalString
	}
	return ""
}

type AutoCompleteResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	PrepositionsStrings []string               `protobuf:"bytes,1,rep,name=PrepositionsStrings,proto3" json:"PrepositionsStrings,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *AutoCompleteResponse) Reset() {
	*x = AutoCompleteResponse{}
	mi := &file_auto_complete_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AutoCompleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AutoCompleteResponse) ProtoMessage() {}

func (x *AutoCompleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auto_complete_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AutoCompleteResponse.ProtoReflect.Descriptor instead.
func (*AutoCompleteResponse) Descriptor() ([]byte, []int) {
	return file_auto_complete_proto_rawDescGZIP(), []int{1}
}

func (x *AutoCompleteResponse) GetPrepositionsStrings() []string {
	if x != nil {
		return x.PrepositionsStrings
	}
	return nil
}

var File_auto_complete_proto protoreflect.FileDescriptor

const file_auto_complete_proto_rawDesc = "" +
	"\n" +
	"\x13auto-complete.proto\x12\rauto_complete\"=\n" +
	"\x13AutoCompleteRequest\x12&\n" +
	"\x0eoriginalString\x18\x01 \x01(\tR\x0eoriginalString\"H\n" +
	"\x14AutoCompleteResponse\x120\n" +
	"\x13PrepositionsStrings\x18\x01 \x03(\tR\x13PrepositionsStrings2n\n" +
	"\x13AutoCompleteService\x12W\n" +
	"\fAutoComplete\x12\".auto_complete.AutoCompleteRequest\x1a#.auto_complete.AutoCompleteResponseB\x1fZ\x1dauto_complete/pkg/proto;protob\x06proto3"

var (
	file_auto_complete_proto_rawDescOnce sync.Once
	file_auto_complete_proto_rawDescData []byte
)

func file_auto_complete_proto_rawDescGZIP() []byte {
	file_auto_complete_proto_rawDescOnce.Do(func() {
		file_auto_complete_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_auto_complete_proto_rawDesc), len(file_auto_complete_proto_rawDesc)))
	})
	return file_auto_complete_proto_rawDescData
}

var file_auto_complete_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_auto_complete_proto_goTypes = []any{
	(*AutoCompleteRequest)(nil),  // 0: auto_complete.AutoCompleteRequest
	(*AutoCompleteResponse)(nil), // 1: auto_complete.AutoCompleteResponse
}
var file_auto_complete_proto_depIdxs = []int32{
	0, // 0: auto_complete.AutoCompleteService.AutoComplete:input_type -> auto_complete.AutoCompleteRequest
	1, // 1: auto_complete.AutoCompleteService.AutoComplete:output_type -> auto_complete.AutoCompleteResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_auto_complete_proto_init() }
func file_auto_complete_proto_init() {
	if File_auto_complete_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_auto_complete_proto_rawDesc), len(file_auto_complete_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_auto_complete_proto_goTypes,
		DependencyIndexes: file_auto_complete_proto_depIdxs,
		MessageInfos:      file_auto_complete_proto_msgTypes,
	}.Build()
	File_auto_complete_proto = out.File
	file_auto_complete_proto_goTypes = nil
	file_auto_complete_proto_depIdxs = nil
}
