CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE list_default_phrases(
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    phrase VARCHAR(100) NOT NULL
);

INSERT INTO list_default_phrases (phrase) VALUES
('apple'),
('application'),
('appreciate'),
('apricot'),
('banana'),
('bandana'),
('batman'),
('barcelona'),
('car'),
('carbonara'),
('cat'),
('caterpillar'),
('chocolate'),
('dolphin'),
('dog'),
('dragon'),
('elephant'),
('eclipse'),
('error'),
('fire'),
('forest'),
('fox'),
('giraffe'),
('guitar'),
('happy'),
('happiness'),
('happy hour'),
('ice cream'),
('internet'),
('island'),
('jungle'),
('juice'),
('kangaroo'),
('kiwi'),
('lion'),
('lemon'),
('mango'),
('monkey'),
('mountain'),
('night'),
('noodle'),
('ocean'),
('orange'),
('panda'),
('python'),
('query'),
('rabbit'),
('rainbow'),
('sunshine'),
('sunset'),
('tiger'),
('tropical'),
('umbrella'),
('unicorn'),
('violin'),
('volcano'),
('waterfall'),
('whale'),
('xenon'),
('yogurt'),
('zebra');